info:
  version: @project.version@
spring:
  application:
    name: springboot-gateway
server:
  port: 8765
    #ssl:
    #key-store: classpath:keystore.jks
    #key-store-password: 123456
    #keyStoreType: JKS
  #key-alias: certificatekey
